tridentctl: Improve error message when fails to execute kubectl
tridentctl currently outputs "could not find the Kubernetes CLI" when
fails to execute kubectl even if kubectl command is found. With this PR,
tridentctl is changed to outputs the following error message if kubectl
is found but it exits with error:

```
$ bin/tridentctl version
Error: could find the Kubernetes CLI, but it exited with error: Unable
to connect to the server: No valid id-token, and cannot refresh without
refresh-token
```